name: DeployPackages

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-preview'

jobs:
  deploy-prerequisite:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Verify tag format and branch
        env:
          CI_COMMIT_TAG: ${{ github.ref_name }}
        run: |
          branches=$(git show --no-patch --format=%D $CI_COMMIT_TAG)
          echo "Branches: $branches"
          echo "Tag: $CI_COMMIT_TAG"
          if [[ $branches == *release* && $CI_COMMIT_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+-preview\.[0-9]+$ ]]; then
            echo "Matched Release preview tag pattern"
            exit 0
          elif [[ $branches == *main* && $CI_COMMIT_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Matched Main tag pattern"
            exit 0
          else
            echo "Created tag does not meet requirements."
            exit 1
          fi
      - name: Check for version match in version.props
        env:
          CI_COMMIT_TAG: ${{ github.ref_name }}
        run: |
          if ! grep -q "$CI_COMMIT_TAG" version.props; then
            echo "Version mismatch: $CI_COMMIT_TAG not found in version.props"
            exit 1
          fi
  deploy-results:
    needs: [deploy-prerequisite]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pack KetPsi.Results
        id: pack-results
        uses: ./.github/workflows/actions/nuget-pack
        with:
          project_path: src/KetPsi.Results/KetPsi.Results.csproj
      - name: Push KetPsi.Results
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
        uses: ./.github/workflows/actions/nuget-push
        with:
          package_path: 'pack/KetPsi.Results.${{ github.ref_name }}.nupkg'

  